version: '3.8'

services:
  stream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream
    stdin_open: true
    tty: true
    volumes:
      - ./:/root/crypto-pipeline
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true
