version: '3'

networks:
  crypto:
    driver: bridge

services:
  alpine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streaming
    stdin_open: true
    tty: true
    networks:
      - crypto
    ports:
      - '9092:9092'
    volumes:
      - ./:/root/crypto-pipeline/streaming
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER