FROM openjdk:17-alpine

WORKDIR /usr/src/crypto-pipeline/streaming

RUN apk update && apk add --no-cache libxext libxrender libxtst libxi freetype libc6-compat bash procps curl gcompat libstdc++

RUN java -version

